### ISSUE TITLE
Not working in Redmine 5

### ISSUE THREAD

**Issue by nanaksingh13** [xmera-circle/redmine_workload#24]
when i install this plugin Redmine crashes.

**Comment by mboremski** [comment]
Could you please give us more informations about your installation and used plugins?
E.g. administration -> information

Thank you

**Comment by mboremski** [comment]
Please also provide logentries.

**Comment by nanaksingh13** [comment]
```
Environment:
  Redmine version                5.0.3.stable
  Ruby version                   2.6.10-p210 (2022-04-12) [x64-mingw32]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Circle (includes JavaScript)
SCM:
  Git                            2.38.0
  Filesystem                     
Redmine plugins:
  easy_baseline                  2.0
  easy_gantt                     2.0
  easy_gantt_pro                 2.0
  redmine_base_deface            1.6.2
  redmine_checklists             3.1.22
  redmine_context_menu_due_date  0.0.1
  redmine_custom_workflows       2.0.8
  redmine_dmsf                   3.0.12
  redmine_impersonate            2.0.0
  redmine_issue_assign_notice    2.1.0
  redmine_issue_dynamic_edit     0.8.1.1
  redmine_issues_tree            0.0.15
  redmine_logs                   0.3.0
  redmine_more_previews          5.0.7
  redmine_subject_autocomplete   1.0.0
  redmine_telegram               0.2
  redmine_user_text_box          0.1.0
  redmine_wysiwyg_editor         0.28.0
```

**Comment by formigadiablo** [comment]
I am having the same problem, when installing everything seems to work perfectly but when I refresh the server, it does not work.

**Comment by mboremski** [comment]
Can you please provide error-messages or similar informations.
This might help to understand whats going on.

Thank you

**Comment by formigadiablo** [comment]
First I install the plugin though this procedure:

> sudo git clone https://github.com/xmera-circle/redmine_workload.git

> sudo bundle install

> sudo rake redmine:plugins:migrate NAME=redmine_workload RAILS_ENV=production

`systemctl` restart apache 2

And no problem seems to arise. Then I restart the server and this message appears.

![image](https://user-images.githubusercontent.com/124778067/233034517-263466c5-ae69-40bc-aa33-e5aabf5c8275.png)


And this is what I can see from production log

W, [2023-04-19T11:34:54.325815 #1373969]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.0. (called from instance_eval at /opt/redmine/redmine-5.0.3/config/routes.rb:402)
W, [2023-04-19T11:34:54.326607 #1373969]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.0. (called from instance_eval at /opt/redmine/redmine-5.0.3/config/routes.rb:402)
W, [2023-04-19T11:34:54.326955 #1373969]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.0. (called from instance_eval at /opt/redmine/redmine-5.0.3/config/routes.rb:402)
W, [2023-04-19T11:34:54.327295 #1373969]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.0. (called from instance_eval at /opt/redmine/redmine-5.0.3/config/routes.rb:402)
W, [2023-04-19T11:34:54.327646 #1373969]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.0. (called from instance_eval at /opt/redmine/redmine-5.0.3/config/routes.rb:402)
W, [2023-04-19T11:34:54.327995 #1373969]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.0. (called from instance_eval at /opt/redmine/redmine-5.0.3/config/routes.rb:402)
W, [2023-04-19T11:34:54.328350 #1373969]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 7.0. (called from instance_eval at /opt/redmine/redmine-5.0.3/config/routes.rb:402)
I, [2023-04-19T11:34:54.550540 #1373969]  INFO -- : Migrating to CreateWlUserVacations (1)
I, [2023-04-19T11:34:54.724540 #1373969]  INFO -- : Migrating to CreateWlUserData (2)
I, [2023-04-19T11:34:54.907889 #1373969]  INFO -- : Migrating to CreateWlNationalHolidays (3)
I, [2023-04-19T11:34:55.041489 #1373969]  INFO -- : Migrating to AddMainGroupToWlUserData (4)
W, [2023-04-19T11:35:22.762615 #1374145]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2023-04-19T11:35:22.784576 #1374145]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2023-04-19T11:35:22.861968 #1374145]  WARN -- : Creating scope :having_mail. Overwriting existing method User.having_mail.
W, [2023-04-19T11:35:23.329119 #1374145]  WARN -- : Creating scope :visible. Overwriting existing method AgileQuery.visible.
W, [2023-04-19T11:35:23.432865 #1374145]  WARN -- : Creating scope :visible. Overwriting existing method Principal.visible.
W, [2023-04-19T11:35:25.434985 #1374145]  WARN -- : Creating scope :global_or_on_project. Overwriting existing method DriveEntryQuery.global_or_on_project.
W, [2023-04-19T11:35:25.435199 #1374145]  WARN -- : Creating scope :sorted. Overwriting existing method DriveEntryQuery.sorted.
W, [2023-04-19T11:35:25.543698 #1374145]  WARN -- : Creating scope :visible. Overwriting existing method PeopleQuery.visible.
W, [2023-04-19T11:35:25.866430 #1374145]  WARN -- : Creating scope :visible. Overwriting existing method WkExpenseEntry.visible.
W, [2023-04-19T11:35:25.866642 #1374145]  WARN -- : Creating scope :left_join_issue. Overwriting existing method WkExpenseEntry.left_join_issue.
W, [2023-04-19T11:35:25.866774 #1374145]  WARN -- : Creating scope :on_issue. Overwriting existing method WkExpenseEntry.on_issue.
W, [2023-04-19T11:35:25.941327 #1374145]  WARN -- : Creating scope :visible. Overwriting existing method WkMaterialEntry.visible.
W, [2023-04-19T11:35:25.941544 #1374145]  WARN -- : Creating scope :left_join_issue. Overwriting existing method WkMaterialEntry.left_join_issue.
W, [2023-04-19T11:35:25.941711 #1374145]  WARN -- : Creating scope :on_issue. Overwriting existing method WkMaterialEntry.on_issue.
W, [2023-04-19T11:38:56.342977 #1374168]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2023-04-19T11:38:56.365127 #1374168]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2023-04-19T11:38:56.444041 #1374168]  WARN -- : Creating scope :having_mail. Overwriting existing method User.having_mail.
W, [2023-04-19T11:38:56.937180 #1374168]  WARN -- : Creating scope :visible. Overwriting existing method AgileQuery.visible.
W, [2023-04-19T11:38:57.020965 #1374168]  WARN -- : Creating scope :visible. Overwriting existing method Principal.visible.
W, [2023-04-19T11:38:59.013285 #1374168]  WARN -- : Creating scope :global_or_on_project. Overwriting existing method DriveEntryQuery.global_or_on_project.
W, [2023-04-19T11:38:59.013493 #1374168]  WARN -- : Creating scope :sorted. Overwriting existing method DriveEntryQuery.sorted.
W, [2023-04-19T11:38:59.124106 #1374168]  WARN -- : Creating scope :visible. Overwriting existing method PeopleQuery.visible.
W, [2023-04-19T11:38:59.461567 #1374168]  WARN -- : Creating scope :visible. Overwriting existing method WkExpenseEntry.visible.
W, [2023-04-19T11:38:59.461792 #1374168]  WARN -- : Creating scope :left_join_issue. Overwriting existing method WkExpenseEntry.left_join_issue.
W, [2023-04-19T11:38:59.461927 #1374168]  WARN -- : Creating scope :on_issue. Overwriting existing method WkExpenseEntry.on_issue.
W, [2023-04-19T11:38:59.538596 #1374168]  WARN -- : Creating scope :visible. Overwriting existing method WkMaterialEntry.visible.
W, [2023-04-19T11:38:59.538816 #1374168]  WARN -- : Creating scope :left_join_issue. Overwriting existing method WkMaterialEntry.left_join_issue.
W, [2023-04-19T11:38:59.538966 #1374168]  WARN -- : Creating scope :on_issue. Overwriting existing method WkMaterialEntry.on_issue.

**Comment by mboremski** [comment]
I can see only warnings there.
Could you please have a look if you missed Error-Messages?
Maybe from your apache-logs?

@nanaksingh13 are you facing similar behaviour?

**Comment by formigadiablo** [comment]
pp 1395844 stdout: 
[ 2023-04-20 08:47:49.2538 1395730/7fdffc509700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/redmine/redmine-5.0.3: An error occurred while starting up the preloader.
  Error ID: 3fa0d195
  Error details saved to: /tmp/passenger-error-4XTQ6L.html
  Message from application: uninitialized constant RedmineWorkload::GroupWorkloadPreparer (NameError)
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
  /var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
  /var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
  /var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
  /var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
  /var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
  /var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
  /opt/redmine/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.7.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `instance_eval'
  /var/lib/gems/2.7.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by liaham** [comment]
Thank you, @formigadiablo!

This line:
```shell
Message from application: uninitialized constant RedmineWorkload::GroupWorkloadPreparer (NameError)
```
is the line causing the error.

This error is already fixed on `develop` branch.

When you don't like to wait, you can try the develop branch and change back to master when the next version is released.

**Comment by formigadiablo** [comment]
Oooh Thank you! Now I was able to install it!!

**Comment by liaham** [comment]
You are welcome! :)

**Comment by Nixan04** [comment]
The application encountered the following error: uninitialized constant RedmineWorkload::GroupWorkloadPreparer (NameError)

I am still facing same problem after using develop branch?
Can you please help me.

**Comment by mboremski** [comment]
@Nixan04 I edited your comment for better readability.

It looks like there is an issue in the format of your date:
`"first_day"=>"2023-0317"`... it should be
`"first_day"=>"2023-03-17"`

Looks like this has nothing to do with redmine5.
If you can not fix it by yourself with my hint please report a new issue to keep this one clean.
